---
abstract: 'build sprintf-like functions of your own'
author:
  - 'Ricardo Signes <rjbs@cpan.org>'
  - 'Darren Chamberlain <darren@cpan.org>'
generated_by: 'Dist::Zilla version 1.093220'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-Formatter
requires:
  Params::Util: 0
  Sub::Exporter: 0
resources:
  repository: http://github.com/rjbs/string-formatter
version: 0.093221
